#!/bin/bash

# This script will check the how many syslog a program is generating.

# Check whether the script is being executed as the root user or not.
if [[ "${UID}" -eq 0 ]]
  then 
    echo "Your are executing the script as a Root user"
  else
    echo "Kindly execute the script as a Root user or using sudo"
fi

# To print the number of syslog being generated by the program.
cat /var/log/syslog | awk '{print$5}' | sort |  uniq -c | sort -n
